import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { RoleEnum } from '@/generated/graphql'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [
            RoleEnum.SuperAdmin,
            RoleEnum.MahalluAdmin,
            RoleEnum.DistrictAdmin,
            RoleEnum.InfoAdmin,
            RoleEnum.VillageAdmin,
            RoleEnum.ZoneAdmin,
        ],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'mahallus',
        path: '/mahallus',
        title: 'Mahallus',
        translateKey: 'nav.mahallus',
        icon: 'mahallu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [
            RoleEnum.SuperAdmin,
            RoleEnum.DistrictAdmin,
            RoleEnum.ZoneAdmin,
            RoleEnum.VillageAdmin,
        ],
        subMenu: [],
    },
    {
        key: 'leaderboard',
        path: '/leaderboard',
        title: 'Leaderboard',
        translateKey: 'nav.leaderboard',
        icon: 'leaderBoard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [
            RoleEnum.SuperAdmin,
            RoleEnum.DistrictAdmin,
            RoleEnum.ZoneAdmin,
            RoleEnum.VillageAdmin,
            RoleEnum.MahalluAdmin,
        ],
        subMenu: [],
    },
    {
        key: 'answer-fatwa',
        path: '/answer-fatwa',
        title: 'Fatwas',
        translateKey: 'nav.answer-fatwa',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RoleEnum.InfoAdmin],
        subMenu: [],
    },
    {
        key: 'view-tasks',
        path: '/view-tasks',
        title: 'Tasks',
        translateKey: 'nav.view-tasks',
        icon: 'task',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RoleEnum.MahalluAdmin],
        subMenu: [],
    },
    {
        key: 'view-other-programs',
        path: '/view-other-programs',
        title: 'Other Programs',
        translateKey: 'nav.view-other-programs',
        icon: 'otherProgram',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RoleEnum.MahalluAdmin],
        subMenu: [],
    },
    {
        key: 'verify-tasks',
        path: '/verify-tasks',
        title: 'Verify Tasks',
        translateKey: 'nav.verify-tasks',
        icon: 'verify',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RoleEnum.VillageAdmin],
        subMenu: [],
    },
    {
        key: 'verify-other-programs',
        path: '/verify-other-programs',
        title: 'Verify Other Programs',
        translateKey: 'nav.verify-other-programs',
        icon: 'verify',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RoleEnum.VillageAdmin],
        subMenu: [],
    },
    {
        key: 'groupMenu',
        path: '',
        title: 'Data Management',
        translateKey: 'nav.dataManagement',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'notifications',
                path: '/notifications',
                title: 'Notifications',
                translateKey: 'nav.notifications',
                icon: 'notification',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'district',
                path: '/district',
                title: 'Districts',
                translateKey: 'nav.district',
                icon: 'district',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'zone',
                path: '/zone',
                title: 'Zones',
                translateKey: 'nav.zone',
                icon: 'zone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin, RoleEnum.DistrictAdmin],
                subMenu: [],
            },
            {
                key: 'village',
                path: '/village',
                title: 'Villages',
                translateKey: 'nav.village',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin, RoleEnum.ZoneAdmin],
                subMenu: [],
            },
            {
                key: 'mahallu',
                path: '/mahallu',
                title: 'Mahallus',
                translateKey: 'nav.mahallu',
                icon: 'mahallu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin, RoleEnum.VillageAdmin],
                subMenu: [],
            },
            {
                key: 'family',
                path: '/family',
                title: 'Families',
                translateKey: 'nav.family',
                icon: 'family',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.MahalluAdmin],
                subMenu: [],
            },
            {
                key: 'committee',
                path: '/committee',
                title: 'Committees',
                translateKey: 'nav.committee',
                icon: 'committee',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.MahalluAdmin],
                subMenu: [],
            },
            {
                key: 'year',
                path: '/year',
                title: 'Years',
                translateKey: 'nav.year',
                icon: 'year',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'badge',
                path: '/badge',
                title: 'Badges',
                translateKey: 'nav.badge',
                icon: 'badge',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'campaign',
                path: '/campaign',
                title: 'Campaigns',
                translateKey: 'nav.campaign',
                icon: 'campaign',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'task',
                path: '/task',
                title: 'Tasks',
                translateKey: 'nav.task',
                icon: 'task',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'task-category',
                path: '/task-category',
                title: 'Task Categories',
                translateKey: 'nav.task-category',
                icon: 'taskCategory',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin],
                subMenu: [],
            },
            {
                key: 'event',
                path: '/event',
                title: 'Events',
                translateKey: 'nav.event',
                icon: 'event',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin, RoleEnum.MahalluAdmin],
                subMenu: [],
            },
            {
                key: 'job',
                path: '/job',
                title: 'Jobs',
                translateKey: 'nav.job',
                icon: 'job',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.SuperAdmin, RoleEnum.MahalluAdmin],
                subMenu: [],
            },
            {
                key: 'post',
                path: '/post',
                title: 'Posts',
                translateKey: 'nav.post',
                icon: 'post',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [RoleEnum.MahalluAdmin],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
