export type Person = {
    id: number
    firstName: string
    lastName: string
    email: string
    status: string
}

export type Option = {
    value: number
    label: string
}

export const data10: Person[] = [
    {
        id: 1,
        firstName: 'Christina',
        lastName: 'Schroeder',
        email: 'lopezmichael@baker.net',
        status: 'rejected',
    },
    {
        id: 2,
        firstName: 'Bianca',
        lastName: 'Cole',
        email: 'rogerskathy@hotmail.com',
        status: 'rejected',
    },
    {
        id: 3,
        firstName: 'Lauren',
        lastName: 'Moss',
        email: 'karlajohnson@marshall.com',
        status: 'accepted',
    },
    {
        id: 4,
        firstName: 'Sarah',
        lastName: 'Griffin',
        email: 'iknight@gmail.com',
        status: 'rejected',
    },
    {
        id: 5,
        firstName: 'Adam',
        lastName: 'Lopez',
        email: 'ryan80@hotmail.com',
        status: 'rejected',
    },
    {
        id: 6,
        firstName: 'Beverly',
        lastName: 'Todd',
        email: 'abigail56@yahoo.com',
        status: 'rejected',
    },
    {
        id: 7,
        firstName: 'Cassandra',
        lastName: 'Robinson',
        email: 'gramirez@yahoo.com',
        status: 'accepted',
    },
    {
        id: 8,
        firstName: 'Nathaniel',
        lastName: 'Shaw',
        email: 'bellmark@wilson.com',
        status: 'rejected',
    },
    {
        id: 9,
        firstName: 'Sandra',
        lastName: 'Bell',
        email: 'reyeskatherine@jennings.net',
        status: 'rejected',
    },
    {
        id: 10,
        firstName: 'Tiffany',
        lastName: 'Gutierrez',
        email: 'rollinschristopher@vincent.com',
        status: 'rejected',
    },
    {
        id: 11,
        firstName: 'John',
        lastName: 'Sandoval',
        email: 'jroth@bennett.biz',
        status: 'rejected',
    },
    {
        id: 12,
        firstName: 'Tyler',
        lastName: 'Wood',
        email: 'austinpeter@gmail.com',
        status: 'pending',
    },
    {
        id: 13,
        firstName: 'Regina',
        lastName: 'Gardner',
        email: 'mollylyons@johnston.com',
        status: 'pending',
    },
    {
        id: 14,
        firstName: 'Erin',
        lastName: 'Long',
        email: 'alexanderwagner@moyer.com',
        status: 'rejected',
    },
    {
        id: 15,
        firstName: 'Brian',
        lastName: 'Scott',
        email: 'mccoyjamie@johnson.com',
        status: 'rejected',
    },
    {
        id: 16,
        firstName: 'Rebecca',
        lastName: 'Smith',
        email: 'murphyjason@hotmail.com',
        status: 'accepted',
    },
    {
        id: 17,
        firstName: 'Billy',
        lastName: 'Gardner',
        email: 'elizabeth35@hotmail.com',
        status: 'accepted',
    },
    {
        id: 18,
        firstName: 'Erin',
        lastName: 'Meadows',
        email: 'etrevino@gmail.com',
        status: 'rejected',
    },
    {
        id: 19,
        firstName: 'Alan',
        lastName: 'Gutierrez',
        email: 'allencheryl@bell.info',
        status: 'rejected',
    },
    {
        id: 20,
        firstName: 'Kyle',
        lastName: 'Pena',
        email: 'teresaboyer@berry.biz',
        status: 'rejected',
    },
    {
        id: 21,
        firstName: 'Benjamin',
        lastName: 'Fischer',
        email: 'lisaleon@king.com',
        status: 'rejected',
    },
    {
        id: 22,
        firstName: 'Bonnie',
        lastName: 'Russo',
        email: 'piercestephanie@gmail.com',
        status: 'accepted',
    },
    {
        id: 23,
        firstName: 'Danielle',
        lastName: 'Martinez',
        email: 'gyoung@larsen.com',
        status: 'rejected',
    },
    {
        id: 24,
        firstName: 'Kimberly',
        lastName: 'Moore',
        email: 'mduke@hotmail.com',
        status: 'pending',
    },
    {
        id: 25,
        firstName: 'Jason',
        lastName: 'Rodriguez',
        email: 'bakerchristine@evans.net',
        status: 'accepted',
    },
    {
        id: 26,
        firstName: 'Charles',
        lastName: 'Wright',
        email: 'stephanieherring@clark.com',
        status: 'rejected',
    },
    {
        id: 27,
        firstName: 'Steven',
        lastName: 'Lucero',
        email: 'susanlopez@whitney-freeman.com',
        status: 'pending',
    },
    {
        id: 28,
        firstName: 'Melissa',
        lastName: 'Tucker',
        email: 'sjenkins@hotmail.com',
        status: 'accepted',
    },
    {
        id: 29,
        firstName: 'Courtney',
        lastName: 'Weiss',
        email: 'theodorejenkins@pineda-simmons.net',
        status: 'accepted',
    },
    {
        id: 30,
        firstName: 'Michael',
        lastName: 'Black',
        email: 'kturner@gmail.com',
        status: 'pending',
    },
    {
        id: 31,
        firstName: 'Joseph',
        lastName: 'Clark',
        email: 'lrasmussen@yahoo.com',
        status: 'rejected',
    },
    {
        id: 32,
        firstName: 'Melissa',
        lastName: 'Strong',
        email: 'stephaniegarcia@hogan-castro.biz',
        status: 'rejected',
    },
    {
        id: 33,
        firstName: 'Shannon',
        lastName: 'Gibbs',
        email: 'ismith@suarez.info',
        status: 'accepted',
    },
    {
        id: 34,
        firstName: 'Ryan',
        lastName: 'Elliott',
        email: 'damon02@lopez-estrada.com',
        status: 'rejected',
    },
    {
        id: 35,
        firstName: 'Kathleen',
        lastName: 'Webb',
        email: 'michaelmacdonald@hotmail.com',
        status: 'rejected',
    },
    {
        id: 36,
        firstName: 'Joshua',
        lastName: 'Hunt',
        email: 'misty22@hotmail.com',
        status: 'pending',
    },
    {
        id: 37,
        firstName: 'Carmen',
        lastName: 'White',
        email: 'plittle@hotmail.com',
        status: 'rejected',
    },
    {
        id: 38,
        firstName: 'Eric',
        lastName: 'Rogers',
        email: 'andersonebony@levy.biz',
        status: 'rejected',
    },
    {
        id: 39,
        firstName: 'Bruce',
        lastName: 'Quinn',
        email: 'jennifer21@yahoo.com',
        status: 'pending',
    },
    {
        id: 40,
        firstName: 'Kenneth',
        lastName: 'Chan',
        email: 'mitchellsandy@allen.biz',
        status: 'pending',
    },
    {
        id: 41,
        firstName: 'Connor',
        lastName: 'Austin',
        email: 'hoopercody@gmail.com',
        status: 'accepted',
    },
    {
        id: 42,
        firstName: 'Charlotte',
        lastName: 'Moore',
        email: 'zpayne@nielsen.com',
        status: 'rejected',
    },
    {
        id: 43,
        firstName: 'Wendy',
        lastName: 'Jackson',
        email: 'jeffreyrussell@gmail.com',
        status: 'rejected',
    },
    {
        id: 44,
        firstName: 'Chelsea',
        lastName: 'Miller',
        email: 'harriscalvin@yahoo.com',
        status: 'pending',
    },
    {
        id: 45,
        firstName: 'Michael',
        lastName: 'Lopez',
        email: 'jack38@gmail.com',
        status: 'rejected',
    },
    {
        id: 46,
        firstName: 'Daniel',
        lastName: 'Bell',
        email: 'zachary20@robinson-grant.biz',
        status: 'pending',
    },
    {
        id: 47,
        firstName: 'Stephen',
        lastName: 'Johnson',
        email: 'ginaoliver@foster.com',
        status: 'pending',
    },
    {
        id: 48,
        firstName: 'Heidi',
        lastName: 'Benitez',
        email: 'cgray@yahoo.com',
        status: 'rejected',
    },
    {
        id: 49,
        firstName: 'Edward',
        lastName: 'Walton',
        email: 'teresa80@stone.net',
        status: 'accepted',
    },
    {
        id: 50,
        firstName: 'Tasha',
        lastName: 'Tran',
        email: 'nathaniel92@pruitt.com',
        status: 'pending',
    },
    {
        id: 51,
        firstName: 'Monica',
        lastName: 'Hernandez',
        email: 'janice32@gmail.com',
        status: 'pending',
    },
    {
        id: 52,
        firstName: 'Kayla',
        lastName: 'Patrick',
        email: 'ssilva@kelly-estrada.com',
        status: 'pending',
    },
    {
        id: 53,
        firstName: 'Amber',
        lastName: 'Gutierrez',
        email: 'enicholson@cisneros.com',
        status: 'rejected',
    },
    {
        id: 54,
        firstName: 'Tara',
        lastName: 'Cooper',
        email: 'reyeswanda@taylor-bennett.com',
        status: 'rejected',
    },
    {
        id: 55,
        firstName: 'Sara',
        lastName: 'Parker',
        email: 'mhughes@gmail.com',
        status: 'accepted',
    },
    {
        id: 56,
        firstName: 'Dustin',
        lastName: 'Ramsey',
        email: 'johnsonrhonda@owens.com',
        status: 'accepted',
    },
    {
        id: 57,
        firstName: 'Keith',
        lastName: 'Morgan',
        email: 'sheila39@morgan.info',
        status: 'rejected',
    },
    {
        id: 58,
        firstName: 'Cynthia',
        lastName: 'Perkins',
        email: 'josephlivingston@herrera.com',
        status: 'rejected',
    },
    {
        id: 59,
        firstName: 'Jennifer',
        lastName: 'Taylor',
        email: 'aromero@gentry-collier.biz',
        status: 'rejected',
    },
    {
        id: 60,
        firstName: 'Bianca',
        lastName: 'Smith',
        email: 'rolson@yahoo.com',
        status: 'rejected',
    },
    {
        id: 61,
        firstName: 'Candice',
        lastName: 'Hernandez',
        email: 'judylucero@hotmail.com',
        status: 'pending',
    },
    {
        id: 62,
        firstName: 'Susan',
        lastName: 'Stevens',
        email: 'carriejones@singh.com',
        status: 'accepted',
    },
    {
        id: 63,
        firstName: 'Kathy',
        lastName: 'Davis',
        email: 'mathew05@salazar-west.net',
        status: 'pending',
    },
    {
        id: 64,
        firstName: 'Cheryl',
        lastName: 'Howard',
        email: 'chasejackson@richmond.biz',
        status: 'rejected',
    },
    {
        id: 65,
        firstName: 'Kristina',
        lastName: 'Jones',
        email: 'spencerpatricia@rodriguez-bailey.com',
        status: 'rejected',
    },
    {
        id: 66,
        firstName: 'Steven',
        lastName: 'Thompson',
        email: 'wallacegabriel@banks.com',
        status: 'accepted',
    },
    {
        id: 67,
        firstName: 'Robert',
        lastName: 'Jackson',
        email: 'nunderwood@gmail.com',
        status: 'pending',
    },
    {
        id: 68,
        firstName: 'Roberto',
        lastName: 'Mitchell',
        email: 'zrobertson@yahoo.com',
        status: 'rejected',
    },
    {
        id: 69,
        firstName: 'Bruce',
        lastName: 'Doyle',
        email: 'danny36@anderson.com',
        status: 'rejected',
    },
    {
        id: 70,
        firstName: 'Brandi',
        lastName: 'Sanchez',
        email: 'cbooth@gmail.com',
        status: 'accepted',
    },
    {
        id: 71,
        firstName: 'Mikayla',
        lastName: 'Flynn',
        email: 'grantjeanette@moore-watson.com',
        status: 'rejected',
    },
    {
        id: 72,
        firstName: 'Catherine',
        lastName: 'Griffith',
        email: 'olsenlindsay@gmail.com',
        status: 'rejected',
    },
    {
        id: 73,
        firstName: 'Michael',
        lastName: 'Rose',
        email: 'sean47@rodriguez.org',
        status: 'rejected',
    },
    {
        id: 74,
        firstName: 'Rebecca',
        lastName: 'Cooke',
        email: 'heather93@yahoo.com',
        status: 'rejected',
    },
    {
        id: 75,
        firstName: 'Gabriel',
        lastName: 'Washington',
        email: 'jeffreyperry@blair.com',
        status: 'rejected',
    },
    {
        id: 76,
        firstName: 'Mary',
        lastName: 'Dunn',
        email: 'hmiles@hotmail.com',
        status: 'rejected',
    },
    {
        id: 77,
        firstName: 'Sabrina',
        lastName: 'Hill',
        email: 'jryan@gmail.com',
        status: 'rejected',
    },
    {
        id: 78,
        firstName: 'Trevor',
        lastName: 'Wallace',
        email: 'kathleen31@hotmail.com',
        status: 'rejected',
    },
    {
        id: 79,
        firstName: 'Steven',
        lastName: 'Rodriguez',
        email: 'kentkayla@hotmail.com',
        status: 'rejected',
    },
    {
        id: 80,
        firstName: 'Cindy',
        lastName: 'Reynolds',
        email: 'hbailey@fuentes.com',
        status: 'accepted',
    },
    {
        id: 81,
        firstName: 'Tracy',
        lastName: 'Rivas',
        email: 'amanda38@hotmail.com',
        status: 'rejected',
    },
    {
        id: 82,
        firstName: 'Amy',
        lastName: 'Smith',
        email: 'atkinsjasmin@gibson-rice.net',
        status: 'rejected',
    },
    {
        id: 83,
        firstName: 'Derrick',
        lastName: 'Smith',
        email: 'iperez@hotmail.com',
        status: 'pending',
    },
    {
        id: 84,
        firstName: 'Carrie',
        lastName: 'Wood',
        email: 'mark74@yahoo.com',
        status: 'pending',
    },
    {
        id: 85,
        firstName: 'David',
        lastName: 'Brown',
        email: 'sanderscaitlin@chandler.com',
        status: 'rejected',
    },
    {
        id: 86,
        firstName: 'Gordon',
        lastName: 'Underwood',
        email: 'brownjamie@rodriguez.net',
        status: 'rejected',
    },
    {
        id: 87,
        firstName: 'Fernando',
        lastName: 'Curtis',
        email: 'imiller@yahoo.com',
        status: 'pending',
    },
    {
        id: 88,
        firstName: 'Jennifer',
        lastName: 'Tran',
        email: 'mitchellmichelle@jones.com',
        status: 'pending',
    },
    {
        id: 89,
        firstName: 'Julie',
        lastName: 'Johnson',
        email: 'josephhernandez@smith.info',
        status: 'rejected',
    },
    {
        id: 90,
        firstName: 'Christina',
        lastName: 'Cole',
        email: 'harrellnancy@conley-fernandez.com',
        status: 'rejected',
    },
]
